# Generated by Django 4.2.26 on 2025-11-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
    ]
